### PR TITLE
Version the Swift dependency using the dev snapshot names

### PR DESCRIPTION
**Pull request by briancroom**
After having worked with this buildpack for a bit, it's becoming clear that a few issues are caused by the current strategy of having a rolling "2.2" version number for Swift which tracks progressive developer snapshots:
- There can be unexpected breakage while Swift versions are changing so rapidly
- Our behavior differs from how the original Heroku buildpack and [swiftenv](https://github.com/kylef/swiftenv) interpret the .swift-version file
- The build cache is not invalidated when a new snapshot version becomes available, so the only way to get the new tools is to delete the app before re-pushing. 

[Others](https://github.com/kylef/Curassow/issues/17) have encountered these problems as well. 

This PR changes to using Apple's snapshot naming as the versioning for the Swift dependency. I'm imagining that we can keep a couple months' worth of the most recent snapshots in the manifest at least until the final 2.2 release and then we can evaluate what makes sense going forward. 

What do you think @drnic?

### CODE REVIEW

**Comment by briancroom** [comment]
Hmm that's interesting. Could you elaborate on how it downgrades the developer experience? I thought the point of version pinning was to ensure consistency and predictability across deploys?

The current reality is that there _is_ no stable release we can point to, which would be a prerequisite for a sane app development experience. As far as I know, there is no intention of breaking changes being introduced to the compiler or stdlib, but these are still development snapshots which will inevitably contain bugs here and there which could break apps. Even more problematic is that the Swift Package Manager at the heart of this buildpack is so fresh that it hasn't seen a single stable release yet, and it isn't scheduled to until the Fall. Breaking changes to its functionality and the Package.swift format are to be entirely expected in the coming weeks before the tool even has a proper version number applied to it. 

If the developer experience is a bit rough currently (I'm not arguing that it isn't!), I'd say that it's because we are building on top of experimental tools that are still in their infancy. At this point all we can do is give devs enough control so as to not get their hands tied while working on the bleeding edge. 

That said, if you think it makes sense to keep the generic 2.2 (or 2.2-dev?) version also, I don't see why not #yolo 😆

Thoughts?

**Comment by briancroom** [comment]
To be clear, I do think that we will have the opportunity to provide a more polished developer UX down the road a bit once we do have stable releases to work with.

**Comment by briancroom** [comment]
I've pushed an update now which allows specifying Swift snapshot versions either as `swift-2.2-SNAPSHOT-2016-01-11-a` or as `2.2-SNAPSHOT-2016-01-11-a` since the `swift-` prefix is rather redundant in a `.swift-version` file (as suggested [here](https://github.com/kylef/Curassow/issues/17#issuecomment-170372345)).

I'd love to get more feedback on this @drnic! (@kylef too)

**Comment by kylef** [comment]
> "you're proposing we downgrade the buildpack user experience and force them to be very very explicit about each swift version to use"

This should be a huge improvement for user experience since currently the build pack refers to "2.2" as a snapshot which won't be what the final 2.2 version will be. These are dev snapshots are moving quickly (one every week or two) and may not be compatible between releases.

> The current reality is that there is no stable release we can point to, which would be a prerequisite for a sane app development experience.

The final release of 2.2 won't include Swift Package Manager and the standard library, and thus the actual "2.2" release will be vastly different from the snapshots. The real release of 2.2 probably won't actually be usable in this build pack since it lacks SPM and the standard library.

Swift 3.0 should actually be the first stable release with Swift Package Manager and the standard library (along with a stable ABI)

Here's an excerpt from the Swift blog on 2.2:

> Swift on Linux will be included in this release. However it is still relatively new and has known caveats. Swift 2.2 will not include the Swift Core Libraries but will include LLDB and the REPL.

[[source](https://swift.org/blog/swift-2-2-release-process/)]

> That said, if you think it makes sense to keep the generic 2.2 (or 2.2-dev?) version also, I don't see why not #yolo

I think this could be a bad idea since 2.2-dev is a moving target and updates to this in the build pack can cause a users web application to no longer work or build. I think this will make sense in the _distant_ future once 3.0 is out, there will be stable releases of `3.0`, `3.1`, etc which can be used in production.

**Comment by briancroom** [comment]
This has been working very smoothly for me for a bit now; I'm going to go ahead and merge it.

I look forward to continue discussing what kind of developer UX we can provide here down the road a bit.

**Pull request merged**
